language: swift
osx_image: xcode10.2
before_script:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -workspace Transportation_PLUS.xcodeproj/project.xcworkspace -scheme Transportation_PLUS -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' build | xcpretty --test --color